sudo: false

language: python
cache: pip
python:
  - 3.6
  - 3.5
  - 3.4
  - 3.3


before_install:
  - pip install -U pip
  - pip install -U -r test_requirements.txt

install: python setup.py develop

script:
  - pytest --verbose --cov=mtg_ssm
  - pylint mtg_ssm
  - pylint --disable=similarities,redefined-outer-name tests
  - flake8
  - pydocstyle

after_script: coveralls
